# Generated by Django 4.2.1 on 2023-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('script', models.CharField(choices=[('players', 'Players'), ('scraper', 'Scraper')], max_length=50)),
                ('changes_detected', models.TextField()),
            ],
        ),
    ]
